# Generated by Django 5.2.1 on 2025-05-16 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_date',
            field=models.DateField(default=datetime.date(2025, 5, 17)),
            preserve_default=False,
        ),
    ]
