# Generated by Django 5.2.1 on 2025-05-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0002_meal_meal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_date',
        ),
    ]
